name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies & Compile
        run: sudo ./build-ubuntu.sh -j4
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-linux-static
          path: ./target/bin/**
  MacOS:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: brew install openssl frei0r sdl2 wget
      - name: Compile
        run: ./build.sh -j4
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-macos-static
          path: ./target/bin/**
          
